FROM node:10.19.0

WORKDIR /app

COPY src/assets/json-files ./json-files

COPY package.json .
COPY package-lock.json .

RUN npm install
RUN npm install -g json-server@0.14.0

EXPOSE 3000

CMD ["json-server", "--watch", "/app/json-files/acme-explorer.json", "--routes", "/app/json-files/routes.json", "-m", "/app/json-files/version.js", "-H", "0.0.0.0"]
